name: Build

on:
  workflow_dispatch:
  push:
    branches: actions
  pull_request:
    branches: actions
  release:
    types: [created]

jobs:
  linux:
    name: Build ${{ matrix.platform }} ${{ matrix.arch }}, ${{ matrix.build_type }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Update system
      run: |
        sudo apt-get update
    - name: Install dependencies (x86)
      run: |
        sudo apt-get update
        sudo apt-get install -y monodevelop
    - name: Build
      shell: bash
      run: make

